spring:
  config:
    activate:
      on-profile: sharding-it

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topics:
      deposit-requested: test-deposit-requested
      deposit-completed: test-deposit-completed
      withdrawal-requested: test-withdrawal-requested
      withdrawal-completed: test-withdrawal-completed
      withdrawal-failed: test-withdrawal-failed
  transaction:
    deposit-fee-percent: 0.00
    withdrawal-fee-percent: 0.01
    transfer-fee-percent: 0.005
    init-request-ttl-minutes: 15

logging:
  level:
    root: WARN
    com.example.transaction: INFO
    org.apache.shardingsphere: INFO
